package config

import (
	"context"
	"errors"
	"fmt"
	"log"
	"net/url"
	"os"
	"runtime/debug"
	"strconv"
	"strings"
	"time"

	"github.com/goccy/go-json"

	"github.com/spf13/viper"
	"github.com/subosito/gotenv"

	"github.com/Faze-Technologies/go-utils/secrets"
)

// Retry knobs for initFromSecretManager, matching loadSecrets.js's actual
// delay values (go-utils/logs isn't available yet here - it imports this
// package, so config can't import it back, hence plain log.Printf below).
const (
	// setSecretManagerClient: fixed delayMs=2000 between attempts.
	secretClientMaxAttempts = 5
	secretClientRetryDelay  = 2 * time.Second

	// loadWithRetries: retryDelay=3000, waitTime = attempts * retryDelay.
	secretFetchMaxAttempts = 5
	secretFetchRetryDelay  = 3 * time.Second

	// loadSecrets: promiseWithTimeout(client.accessSecretVersion(...), 2000).
	secretFetchTimeout = 2 * time.Second
)

// environmentProjects maps an ENVIRONMENT value to the GCP project that
// holds its secrets. Add new environments here only — nothing else in this
// file needs to change per environment or per service.
var environmentProjects = map[string]string{
	"dev":     "prj-fc-dev",
	"preprod": "prj-fc-pre-prod",
	"prod":    "prj-fc-prod",
}

// secretConfigKey and mongodbKey get special handling in initFromSecretManager
// (see the switch there); every other SECRETS_CONFIG entry is merged as-is.
const (
	secretConfigKey = "secretConfig"
	mongodbKey      = "mongodb"
)

func Get(key string) interface{} {
	return viper.Get(key)
}

func GetString(key string) string {
	return viper.GetString(key)
}

func GetBool(key string) bool {
	return viper.GetBool(key)
}

func GetInt(key string) int {
	return viper.GetInt(key)
}

func GetFloat64(key string) float64 {
	return viper.GetFloat64(key)
}

func GetMap(key string) map[string]interface{} {
	return viper.GetStringMap(key)
}

func GetStringMap(key string) map[string]string {
	return viper.GetStringMapString(key)
}

func GetSlice(key string) []string {
	return viper.GetStringSlice(key)
}

// IsSet reports whether key has an explicit value in config, as opposed to
// GetInt/GetString/etc. silently returning their zero value for an absent
// key. Use this when the zero value is itself a meaningful setting (e.g.
// minPoolSize: 0) and callers need to distinguish "unset, use driver
// default" from "explicitly set to zero".
func IsSet(key string) bool {
	return viper.IsSet(key)
}

// Init loads config. ENVIRONMENT/SERVICE_MODE/IS_LOCAL_DEVELOPMENT come from
// env vars, defaulting to dev/rest/false. The default is skipped when CONFIG
// or ENV_FILE is set, so a service already on the legacy path is never
// redirected here.
func Init() {
	_ = gotenv.Load(".env") // best-effort: fine if it doesn't exist (e.g. in k8s)

	if os.Getenv("CONFIG") == "" && os.Getenv("ENV_FILE") == "" {
		env := os.Getenv("ENVIRONMENT")
		if env == "" {
			env = "dev"
		}
		serviceMode := os.Getenv("SERVICE_MODE")
		if serviceMode == "" {
			serviceMode = "rest"
		}
		isLocalDevelopment := os.Getenv("IS_LOCAL_DEVELOPMENT") == "true"
		initFromSecretManager(env, serviceMode, isLocalDevelopment)
		return
	}

	envFile := os.Getenv("ENV_FILE")
	if envFile == "" {
		envVar := "CONFIG"
		jsonConfig := os.Getenv(envVar)
		if jsonConfig == "" {
			panic(fmt.Errorf("environment variable %s not set", envVar))
		}
		var configMap map[string]interface{}
		if err := json.Unmarshal([]byte(jsonConfig), &configMap); err != nil {
			panic(fmt.Errorf("failed to unmarshal JSON from environment variable: %w", err))
		}
		viper.SetConfigType("json")
		if err := viper.MergeConfigMap(configMap); err != nil {
			panic(fmt.Errorf("failed to merge config map into Viper: %w", err))
		}
	} else {
		reader, err := os.Open(fmt.Sprintf("./env.%s.json", envFile))
		if err != nil {
			panic(fmt.Errorf("unable to read config file\n %w", err))
		}
		viper.SetConfigType("json")
		if err := viper.MergeConfig(reader); err != nil {
			panic(fmt.Errorf("failed to merge config map into Viper: %w", err))
		}
	}
}

// secretConfigItem mirrors the SECRETS_CONFIG entries cmd/generate-env
// writes and loadSecrets.js already consumes: key is the literal Secret
// Manager secret name, env is where its value lands, parseJson says
// whether it's a JSON blob or a plain string.
type secretConfigItem struct {
	Key       string `json:"key"`
	Env       string `json:"env"`
	ParseJSON bool   `json:"parseJson"`
}

// initFromSecretManager loads config for env (dev/preprod/prod) by walking
// the SECRETS_CONFIG list (from .env, generated by cmd/generate-env) and
// fetching each named secret from Secret Manager - the same list and the
// same secrets the JS services already read via loadSecrets.js. secretConfig
// merges in as the base config; mongodb gets special handling to turn its
// shared mongodb_clusterUrls map + credentials into this service's
// mongodb.host/user/password; everything else merges under its own Env key.
func initFromSecretManager(env, serviceMode string, isLocalDevelopment bool) {
	project, ok := environmentProjects[env]
	if !ok {
		panic(fmt.Errorf("unknown ENVIRONMENT %q, expected one of dev/preprod/prod", env))
	}

	raw := os.Getenv("SECRETS_CONFIG")
	if raw == "" {
		panic(fmt.Errorf("SECRETS_CONFIG not set - run `go run github.com/Faze-Technologies/go-utils/cmd/generate-env` to generate .env"))
	}
	var items []secretConfigItem
	if err := json.Unmarshal([]byte(raw), &items); err != nil {
		panic(fmt.Errorf("failed to parse SECRETS_CONFIG: %w", err))
	}

	serviceName := currentServiceName()

	log.Println("🔄 Starting secrets loading process")
	log.Println("📦 Setting secret manager client")

	ctx := context.Background()
	client, err := newSecretManagerClientWithRetry()
	if err != nil {
		panic(fmt.Errorf("failed to create Secret Manager client: %w", err))
	}
	defer client.Close()

	log.Printf("📦 Loading %d secrets...", len(items))

	viper.SetConfigType("json")
	for _, item := range items {
		value, err := fetchSecretWithRetry(ctx, client, secretVersionName(project, item.Key))
		if err != nil {
			panic(fmt.Errorf("failed to fetch %q secret: %w", item.Key, err))
		}

		if !item.ParseJSON {
			viper.Set(item.Env, strings.TrimSpace(value))
			if item.Env == "stage" {
				viper.Set("environment", strings.TrimSpace(value))
			}
			continue
		}

		var parsed map[string]interface{}
		if err := json.Unmarshal([]byte(value), &parsed); err != nil {
			panic(fmt.Errorf("failed to parse %q secret: %w", item.Key, err))
		}

		// Redis secrets (redis/challengeRedis/superteamRedis, picked by
		// service family - see item.Key) hold split read/write endpoints.
		// go-utils/cache is a single client with no read/write routing, so
		// use the write endpoint - it can always serve reads too.
		if item.Env == "redis" {
			write, _ := parsed["write"].(map[string]interface{})
			host, _ := write["host"].(string)
			if host == "" {
				panic(fmt.Errorf("no write.host in %q secret", item.Key))
			}
			viper.Set("redis.address", fmt.Sprintf("%v:%v", host, write["port"]))
			viper.Set("redis.password", write["password"])
			continue
		}

		switch item.Key {
		case secretConfigKey:
			if err := viper.MergeConfigMap(parsed); err != nil {
				panic(fmt.Errorf("failed to merge %q secret: %w", item.Key, err))
			}
		case mongodbKey:
			// mongodb_clusterUrls values are already host:port/db?query tails
			// (e.g. "172.16.0.74:27017/analytics-service?retryWrites=..."),
			// keyed by the camelCase service name (InternalServices
			// convention), not the kebab-case module/repo name.
			clusterURLs, _ := parsed["mongodb_clusterUrls"].(map[string]interface{})
			camelName := kebabToCamel(serviceName)
			tail, _ := clusterURLs[camelName].(string)
			if tail == "" {
				panic(fmt.Errorf("no mongodb cluster URL for service %q (key %q) in %q secret", serviceName, camelName, item.Key))
			}
			suffix, _ := parsed["mongodb_suffix"].(string)
			if suffix == "" {
				suffix = "mongodb+srv"
			}
			// Every mongo user is provisioned on the admin database
			// regardless of which database it has roles on - the tail's own
			// query string doesn't include this, so add it if missing.
			if !strings.Contains(tail, "authSource") {
				sep := "&"
				if !strings.Contains(tail, "?") {
					sep = "?"
				}
				tail += sep + "authSource=admin"
			}
			username, _ := parsed["mongodb_username"].(string)
			password, _ := parsed["mongodb_password"].(string)
			viper.Set("mongodb.uri", fmt.Sprintf("%s://%s:%s@%s", suffix, username, url.PathEscape(password), tail))

			// The tail's path segment (before any query string) is the
			// database name - every model reads it separately via
			// mongodb.database (client.Database(...)), not from the URI.
			if slash := strings.Index(tail, "/"); slash != -1 {
				dbName := tail[slash+1:]
				if q := strings.Index(dbName, "?"); q != -1 {
					dbName = dbName[:q]
				}
				viper.Set("mongodb.database", dbName)
			}
		default:
			if err := viper.MergeConfigMap(map[string]interface{}{item.Env: parsed}); err != nil {
				panic(fmt.Errorf("failed to merge %q secret: %w", item.Key, err))
			}
		}
	}
	log.Println("✅ Secrets loaded successfully")

	viper.Set("serviceName", serviceName)
	viper.Set("serviceMode", serviceMode)
	viper.Set("isLocalDevelopment", isLocalDevelopment)

	// Make every OS env var (ENVIRONMENT, SECRETS_CONFIG, anything from
	// .env, etc.) readable through config.Get* too, not just via os.Getenv.
	// A JSON-object value (e.g. .env's SERVER='{"port":":8080",...}') merges
	// under its own key instead of landing as a flat string.
	for _, kv := range os.Environ() {
		key, value, ok := strings.Cut(kv, "=")
		if !ok {
			continue
		}
		var parsed map[string]interface{}
		if err := json.Unmarshal([]byte(value), &parsed); err == nil {
			_ = viper.MergeConfigMap(map[string]interface{}{key: parsed})
			continue
		}
		viper.Set(key, value)
	}

	// OTEL_EXPORTER_OTLP_ENDPOINT is the OpenTelemetry-standard env var name
	// for the collector endpoint; APM_ENABLED/SERVICENAME are ours. All three
	// land as flat env vars, not nested JSON, so map them into apm.* here -
	// that's what apm.InitTracerProvider actually reads.
	if v := os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT"); v != "" {
		viper.Set("apm.otlpEndpoint", v)
	}
	if v := os.Getenv("APM_ENABLED"); v != "" {
		viper.Set("apm.enabled", v == "true")
	}
	if v := os.Getenv("SERVICENAME"); v != "" {
		viper.Set("apm.serviceName", v)
	}

	// PORT/READ_TIMEOUT/WRITE_TIMEOUT are flat env vars (see
	// cmd/generate-env), mapped into server.* here - what main.go's
	// startRESTServer/startGRPCServer actually read.
	if v := os.Getenv("PORT"); v != "" {
		viper.Set("server.port", v)
	}
	if v := os.Getenv("READ_TIMEOUT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			viper.Set("server.readTimeout", n)
		}
	}
	if v := os.Getenv("WRITE_TIMEOUT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			viper.Set("server.writeTimeout", n)
		}
	}

	// ponytail: debug-only dump of the fully resolved config, remove once
	// you're done inspecting it.
	if debugJSON, err := json.MarshalIndent(viper.AllSettings(), "", "  "); err == nil {
		_ = os.WriteFile("config.debug.json", debugJSON, 0644)
	}
}

func secretVersionName(project, secret string) string {
	return fmt.Sprintf("projects/%s/secrets/%s/versions/latest", project, secret)
}

// firstLine trims an error down to its first line - GCP client errors pile
// multi-line "error details: ..." blocks (ErrorInfo/Help/LocalizedMessage)
// onto err.Error(), which floods retry logs; the first line already has the
// actual reason (e.g. "PermissionDenied desc = ...").
func firstLine(err error) string {
	msg := err.Error()
	if i := strings.IndexByte(msg, '\n'); i != -1 {
		msg = msg[:i]
	}
	return msg
}

// newSecretManagerClientWithRetry mirrors loadSecrets.js's
// setSecretManagerClient: retry client creation a few times before giving
// up, since it's a network call (ADC lookup, first RPC) that can
// transiently fail. Fixed delay between attempts, same as
// setSecretManagerClient's delayMs=2000.
func newSecretManagerClientWithRetry() (*secrets.SecretManagerClient, error) {
	var lastErr error
	for attempt := 1; attempt <= secretClientMaxAttempts; attempt++ {
		client, err := secrets.NewSecretManagerClient()
		if err == nil {
			return client, nil
		}
		lastErr = err
		log.Printf("⚠️  setSecretManagerClient failed (attempt %d), retrying...", attempt)
		if attempt < secretClientMaxAttempts {
			time.Sleep(secretClientRetryDelay)
		}
	}
	return nil, fmt.Errorf("all %d attempts failed: %s", secretClientMaxAttempts, firstLine(lastErr))
}

// fetchSecretWithRetry mirrors loadSecrets.js's per-secret retry: each
// attempt is bounded by secretFetchTimeout, up to secretFetchMaxAttempts
// total, with a delay that grows linearly with the attempt number (same as
// loadWithRetries's `waitTime = attempts * retryDelay`).
func fetchSecretWithRetry(ctx context.Context, client *secrets.SecretManagerClient, name string) (string, error) {
	var lastErr error
	for attempt := 1; attempt <= secretFetchMaxAttempts; attempt++ {
		attemptCtx, cancel := context.WithTimeout(ctx, secretFetchTimeout)
		value, err := client.GetSecret(attemptCtx, name)
		cancel()
		if err == nil {
			return value, nil
		}
		lastErr = err
		if errors.Is(attemptCtx.Err(), context.DeadlineExceeded) {
			log.Printf("⏱️  Timeout on %s: %s", name, firstLine(err))
		} else {
			log.Printf("❌ Error on %s: %s", name, firstLine(err))
		}
		if attempt < secretFetchMaxAttempts {
			wait := time.Duration(attempt) * secretFetchRetryDelay
			log.Printf("⚠️  Attempt failed. Retrying in %ds...", int(wait.Seconds()))
			time.Sleep(wait)
		}
	}
	return "", fmt.Errorf("secret %q: all %d attempts failed: %s", name, secretFetchMaxAttempts, firstLine(lastErr))
}

// kebabToCamel converts a kebab-case module/repo name (e.g.
// "cm-miscellaneous-service") to the camelCase form used as map keys inside
// shared secrets like mongodb_clusterUrls - the same convention already used
// for InternalServices keys (e.g. "cmMiscellaneousService").
func kebabToCamel(s string) string {
	parts := strings.Split(s, "-")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// currentServiceName derives the service name from the Go module path
// (e.g. "github.com/Faze-Technologies/cm-miscellaneous-service" ->
// "cm-miscellaneous-service"), so every service gets this for free.
func currentServiceName() string {
	info, ok := debug.ReadBuildInfo()
	if !ok || info.Main.Path == "" {
		panic(fmt.Errorf("unable to determine service name from build info"))
	}
	parts := strings.Split(info.Main.Path, "/")
	return parts[len(parts)-1]
}

func GetServiceURL(service string) string {
	isLocal := viper.GetBool("isLocalDevelopment")
	stage := viper.GetString("environment")

	if isLocal {
		proxies := ProxyServices(stage)
		return proxies[service]
	}

	return InternalServices[service]
}

func MergeConfigFromFilePath(key string, path string) {
	viper.SetConfigType("json")
	reader, err := os.Open(path)
	if err != nil {
		panic(fmt.Errorf("unable to read config file\n %w", err))
	}

	var configMap map[string]interface{}
	err = json.NewDecoder(reader).Decode(&configMap)
	if err != nil {
		panic(fmt.Errorf("unable to decode config file\n %w", err))
	}
	viper.Set(key, configMap)
}

func formatEnvKeys(envData []byte) []byte {
	formattedEnv := make([]byte, 0, len(envData))
	data := strings.Split(string(envData), "\n")
	for _, line := range data {
		if line == "" {
			continue
		}
		splits := strings.SplitN(line, "=", 2)
		newKKey := strings.ReplaceAll(splits[0], "_", ".")
		formattedEnv = append(formattedEnv, []byte(newKKey+"="+splits[1]+"\n")...)
	}
	return formattedEnv
}
